{{- if eq .Values.config.storage.engine "blocks" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-store-gateway.fullname" . }}
  labels: {{ include "cortex-store-gateway.labels" . | nindent 4 }}
    {{- with .Values.store_gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.store_gateway.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{- include "cortex-store-gateway.matchLabels" . | nindent 4 }}
{{- end -}}
