{{- if .Values.ruler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cortex-ruler.fullname" . }}
  labels: {{ include "cortex-ruler.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ruler.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.ruler.replicas }}
  selector:
    matchLabels: {{ include "cortex-ruler.matchLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.ruler.strategy | nindent 4 }}
  template:
    metadata:
      labels: {{ include "cortex-ruler.labels" . | nindent 8 }}
        {{- with .Values.ruler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "cortex.configChecksum" . }}
        {{- with .Values.ruler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.ruler.serviceAccount.name | default (include "cortex.serviceAccountName" . ) }}
    {{- if .Values.ruler.priorityClassName }}
      priorityClassName: {{ .Values.ruler.priorityClassName }}
    {{- end }}
      securityContext: {{- toYaml .Values.ruler.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.ruler.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        {{- if .Values.ruler.sidecar.enabled }}
        - name: {{ template "cortex.name" . }}-sc-rules
          {{- if .Values.ruler.sidecar.image.sha }}
          image: "{{ .Values.ruler.sidecar.image.repository }}:{{ .Values.ruler.sidecar.image.tag }}@sha256:{{ .Values.ruler.sidecar.image.sha }}"
          {{- else }}
          image: "{{ .Values.ruler.sidecar.image.repository }}:{{ .Values.ruler.sidecar.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.ruler.sidecar.imagePullPolicy }}
          env:
            {{- if .Values.ruler.sidecar.watchMethod }}
            - name: METHOD
              value: {{ .Values.ruler.sidecar.watchMethod }}
            {{ end }}
            - name: LABEL
              value: "{{ .Values.ruler.sidecar.label }}"
            {{- if .Values.ruler.sidecar.labelValue }}
            - name: LABEL_VALUE
              value: {{ quote .Values.ruler.sidecar.labelValue }}
            {{- end }}
            - name: FOLDER
              value: "{{ .Values.ruler.sidecar.folder }}{{- with .Values.ruler.sidecar.defaultFolderName }}/{{ . }}{{- end }}"
            - name: RESOURCE
              value: "both"
            {{- if .Values.ruler.sidecar.enableUniqueFilenames }}
            - name: UNIQUE_FILENAMES
              value: "{{ .Values.ruler.sidecar.enableUniqueFilenames }}"
            {{- end }}
            {{- if .Values.ruler.sidecar.searchNamespace }}
            - name: NAMESPACE
              value: "{{ .Values.ruler.sidecar.searchNamespace }}"
            {{- end }}
            {{- if .Values.ruler.sidecar.skipTlsVerify }}
            - name: SKIP_TLS_VERIFY
              value: "{{ .Values.ruler.sidecar.skipTlsVerify }}"
            {{- end }}
            {{- if .Values.ruler.sidecar.folderAnnotation }}
            - name: FOLDER_ANNOTATION
              value: "{{ .Values.ruler.sidecar.folderAnnotation }}"
          {{- end }}
          resources:
            {{- toYaml .Values.ruler.sidecar.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.ruler.sidecar.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: sc-rules-volume
              mountPath: {{ .Values.ruler.sidecar.folder | quote }}
        {{- end }}
        - name: ruler
          image: "{{ .Values.image.repository }}:{{ include "cortex.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=ruler"
            - "-config.file=/etc/cortex/cortex.yaml"
            {{- if .Values.configs.enabled }}
            - "-ruler.configs.url=http://{{ template "cortex-configs.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}"
            {{- end }}
            {{- if not .Values.config.ruler.alertmanager_url }}
            {{- if .Values.config.ruler.enable_alertmanager_discovery }}
            - "-ruler.alertmanager-discovery=true"
            - "-ruler.alertmanager-url=http://_http-metrics._tcp.{{ template "cortex-alertmanager.headlessname" . }}{{ .Values.config.alertmanager.external_url }}/"
            {{- else }}
            - "-ruler.alertmanager-url=http://{{ template "cortex-alertmanager.headlessname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.http_listen_port }}{{ .Values.config.alertmanager.external_url }}/"
            {{- end }}
            {{- end }}
            {{- if and (eq .Values.config.storage.engine "blocks") (not .Values.config.store_gateway.sharding_enabled) }}
            - "-querier.store-gateway-addresses=dns+{{ template "cortex-store-gateway.headlessname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.config.server.grpc_listen_port }}"
            {{- end }}
            {{- include "cortex.memcached" . | nindent 12}}
          {{- range $key, $value := .Values.ruler.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.ruler.extraVolumeMounts }}
            {{- toYaml .Values.ruler.extraVolumeMounts | nindent 12}}
            {{- end }}
            {{- if .Values.ruler.sidecar.enabled }}
            - name: sc-rules-volume
              mountPath: {{ .Values.ruler.sidecar.folder | quote }}
            {{ end }}
            - name: config
              mountPath: /etc/cortex
            - name: runtime-config
              mountPath: /etc/cortex-runtime-config
            - name: storage
              mountPath: /data
              subPath: {{ .Values.ruler.persistentVolume.subPath }}
            - name: tmp
              mountPath: /rules
            {{- range $dir, $_ := .Values.ruler.directories }}
            - name: {{ include "cortex.rulerRulesDirName" $dir }}
              mountPath: /etc/cortex/rules/{{ $dir }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
            - name: gossip
              containerPort: {{ .Values.config.memberlist.bind_port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.ruler.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.ruler.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ruler.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ruler.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.ruler.containerSecurityContext | nindent 12 }}
          {{- if .Values.ruler.env }}
          env:
            {{- toYaml .Values.ruler.env | nindent 12 }}
          {{- end }}
        {{- if .Values.ruler.extraContainers }}
        {{- toYaml .Values.ruler.extraContainers | nindent 8}}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.ruler.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.ruler.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.ruler.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.ruler.terminationGracePeriodSeconds }}
      volumes:
        {{- include "cortex.configVolume" . | nindent 8 }}
        - name: runtime-config
          configMap:
            name: {{ template "cortex.runtimeconfigname" . }}
        - name: tmp
          emptyDir: {}
        {{- range $dir, $_ := .Values.ruler.directories }}
        - name: {{ include "cortex-ruler.dirName" $dir }}
          configMap:
            name: {{ include "cortex.rulerFullname" $ }}-{{ include "cortex-ruler.dirName" $dir }}
        {{- end }}
        - name: storage
          emptyDir: {}
        {{- if .Values.ruler.sidecar.enabled }}
        - name: sc-rules-volume
          emptyDir: {}
        {{- end }}
        {{- if .Values.ruler.extraVolumes }}
        {{- toYaml .Values.ruler.extraVolumes | nindent 8}}
        {{- end }}
{{- end }}
