apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex-ingester.fullname" . }}
  labels: {{ include "cortex-ingester.labels" . | nindent 4 }}
    {{- with .Values.ingester.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ingester.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector: {{- include "cortex-ingester.matchLabels" . | nindent 4 }}
